// <auto-generated />
using System;
using GerenciadorDeEstufasAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciadorDeEstufasAPI.Migrations
{
    [DbContext(typeof(GerenciadorContext))]
    partial class GerenciadorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GerenciadorDeEstufas.Estufa.Amostra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("EstufaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumeroBadeja")
                        .HasColumnType("int");

                    b.Property<int>("NumeroFileira")
                        .HasColumnType("int");

                    b.Property<int>("Posicao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstufaId");

                    b.ToTable("Amostras");
                });

            modelBuilder.Entity("GerenciadorDeEstufas.Estufa.Estufa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumeroDeAmostrasPorFileira")
                        .HasColumnType("int");

                    b.Property<int>("NumeroDeBandejas")
                        .HasColumnType("int");

                    b.Property<int>("NumeroDeIdentificacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Estufas");
                });

            modelBuilder.Entity("GerenciadorDeEstufas.Estufa.Amostra", b =>
                {
                    b.HasOne("GerenciadorDeEstufas.Estufa.Estufa", null)
                        .WithMany("Amostras")
                        .HasForeignKey("EstufaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GerenciadorDeEstufas.Estufa.Estufa", b =>
                {
                    b.Navigation("Amostras");
                });
#pragma warning restore 612, 618
        }
    }
}
